"""Localized strings for the native macOS app."""

from __future__ import annotations

ONBOARDING_STRINGS: dict[str, dict[str, str]] = {
    "en": {
        "accessibility_body": (
            "Allow PtarmiganFlow to control the active text field for voice input output."
        ),
        "accessibility_title": "Accessibility Access",
        "allow_button": "Allow",
        "all_permissions_granted_started_message": (
            "All permissions granted. Voice input started."
        ),
        "app_setup_title": "PtarmiganFlow Setup",
        "choose_language_body": "Select the transcription language to save into your config.",
        "choose_language_title": "Choose Language",
        "config_opened_message": "Opened config: {path}",
        "daemon_not_running_message": "Voice input daemon is not running yet.",
        "daemon_start_failed_message": "Could not start voice input: {error}",
        "dictation_running_menu": "Voice input running",
        "dictation_stopped_message": "Voice input stopped.",
        "dictation_stopped_menu": "Voice input stopped",
        "download_complete_message": "Download complete.",
        "download_failed_message": "Model download failed: {error}",
        "download_in_progress_message": "Downloading model... {percent}",
        "download_preparing_message": "Preparing model...",
        "dictionary_add_exact_button": "Add Exact",
        "dictionary_add_regex_button": "Add Regex",
        "dictionary_canonical_label": "Canonical",
        "dictionary_candidates_patterns_label": "Candidates / Patterns (comma-separated)",
        "dictionary_default_candidate": "candidate",
        "dictionary_default_pattern": "pattern",
        "dictionary_delete_button": "Delete",
        "dictionary_editor_title": "Dictionary Editor",
        "dictionary_exact_rules_title": "Exact Rules",
        "dictionary_invalid_rule_message": (
            "Invalid dictionary rule: [{section}] {key} {pattern}: {message}"
        ),
        "dictionary_load_failed_message": "Could not load dictionary: {error}",
        "dictionary_new_exact_rule": "New Exact Rule",
        "dictionary_new_regex_rule": "New Regex Rule",
        "dictionary_no_rules": "No rules yet.",
        "dictionary_regex_rules_title": "Regex Rules",
        "dictionary_save_button": "Save",
        "dictionary_save_failed_message": "Could not save dictionary: {error}",
        "dictionary_saved_message": (
            "Dictionary saved. Restart voice input to apply changes."
        ),
        "done_body": "Setup is complete. Start voice input or adjust settings.",
        "done_title": "Ready for Voice Input",
        "edit_dictionary_menu": "Edit Dictionary",
        "grant_permissions_message": "Grant all permissions before starting voice input.",
        "input_monitoring_body": "Allow PtarmiganFlow to detect the push-to-talk hotkey.",
        "input_monitoring_title": "Input Monitoring",
        "language_chinese": "Chinese",
        "language_english": "English",
        "language_japanese": "Japanese",
        "language_save_failed_message": "Could not save language: {error}",
        "language_saved_message": "Saved language to {path}.",
        "login_at_startup_button": "Login at Startup",
        "login_at_startup_menu": "Login at Startup",
        "login_disable_failed_message": "Could not disable login at startup.",
        "login_disabled_message": "Login at startup disabled.",
        "login_enable_failed_message": "Could not enable login at startup.",
        "login_enabled_message": "Login at startup enabled.",
        "microphone_body": "Allow PtarmiganFlow to capture audio while you hold the hotkey.",
        "microphone_title": "Microphone Access",
        "model_unavailable_message": (
            "The configured model {model} is not available in this app build. "
            "Choose a model in Settings."
        ),
        "open_config_advanced_button": "Open Config File (Advanced)",
        "open_system_settings_button": "Open System Settings",
        "output_clipboard_paste": "Clipboard Paste",
        "output_direct_typing": "Direct Typing",
        "quit_menu": "Quit",
        "restart_app_button": "Restart App",
        "restart_failed_message": "Could not restart app.",
        "restart_required_note": (
            "If you just granted this in System Settings, you may need to restart the app to "
            "apply it."
        ),
        "settings_button": "Settings",
        "settings_hotkey_label": "Hotkey",
        "settings_language_label": "Language",
        "settings_load_failed_message": "Could not load settings: {error}",
        "settings_menu": "Settings",
        "settings_model_label": "Model",
        "settings_no_models_message": "No bundled speech models are available.",
        "settings_output_mode_label": "Output mode",
        "settings_save_button": "Save",
        "settings_save_failed_message": "Could not save settings: {error}",
        "settings_saved_message": "Settings saved. Restart voice input to apply changes.",
        "settings_validation_error": "Could not save settings. Check: {fields}",
        "settings_window_title": "Settings",
        "start_dictation_button": "Start Voice Input",
        "stop_dictation_button": "Stop Voice Input",
        "voice_input_started_message": "Voice input started.",
    },
    "ja": {
        "accessibility_body": (
            "音声入力の結果を入力するため、PtarmiganFlow が"
            "アクティブなテキスト欄を操作することを許可します。"
        ),
        "accessibility_title": "アクセシビリティへのアクセス",
        "allow_button": "許可する",
        "all_permissions_granted_started_message": (
            "すべての権限が許可されました。音声入力を開始しました。"
        ),
        "app_setup_title": "PtarmiganFlow セットアップ",
        "choose_language_body": "文字起こしに使う言語を選択して設定に保存します。",
        "choose_language_title": "言語を選択",
        "config_opened_message": "設定ファイルを開きました: {path}",
        "daemon_not_running_message": "音声入力デーモンはまだ起動していません。",
        "daemon_start_failed_message": "音声入力を開始できませんでした: {error}",
        "dictation_running_menu": "音声入力 実行中",
        "dictation_stopped_message": "音声入力を停止しました。",
        "dictation_stopped_menu": "音声入力 停止中",
        "download_complete_message": "ダウンロードが完了しました。",
        "download_failed_message": "モデルのダウンロードに失敗しました: {error}",
        "download_in_progress_message": "モデルをダウンロード中... {percent}",
        "download_preparing_message": "モデルを準備中...",
        "dictionary_add_exact_button": "完全一致を追加",
        "dictionary_add_regex_button": "正規表現を追加",
        "dictionary_canonical_label": "正規表記",
        "dictionary_candidates_patterns_label": "候補/パターン(カンマ区切り)",
        "dictionary_default_candidate": "候補",
        "dictionary_default_pattern": "パターン",
        "dictionary_delete_button": "削除",
        "dictionary_editor_title": "変換辞書",
        "dictionary_exact_rules_title": "完全一致ルール",
        "dictionary_invalid_rule_message": (
            "無効な辞書ルール: [{section}] {key} {pattern}: {message}"
        ),
        "dictionary_load_failed_message": "変換辞書を読み込めませんでした: {error}",
        "dictionary_new_exact_rule": "新しい完全一致ルール",
        "dictionary_new_regex_rule": "新しい正規表現ルール",
        "dictionary_no_rules": "ルールがありません",
        "dictionary_regex_rules_title": "正規表現ルール",
        "dictionary_save_button": "保存",
        "dictionary_save_failed_message": "変換辞書を保存できませんでした: {error}",
        "dictionary_saved_message": "保存しました。反映には音声入力を再起動してください。",
        "done_body": "セットアップが完了しました。音声入力を開始するか、設定を変更できます。",
        "done_title": "音声入力の準備完了",
        "edit_dictionary_menu": "変換辞書を編集",
        "grant_permissions_message": "音声入力を開始する前にすべての権限を許可してください。",
        "input_monitoring_body": (
            "プッシュトゥトーク用のホットキーを検出するため、"
            "PtarmiganFlow に入力監視を許可します。"
        ),
        "input_monitoring_title": "入力監視",
        "language_chinese": "中国語",
        "language_english": "英語",
        "language_japanese": "日本語",
        "language_save_failed_message": "言語設定を保存できませんでした: {error}",
        "language_saved_message": "{path} に言語設定を保存しました。",
        "login_at_startup_button": "ログイン時に起動",
        "login_at_startup_menu": "ログイン時に起動",
        "login_disable_failed_message": "ログイン時に起動する設定を無効にできませんでした。",
        "login_disabled_message": "ログイン時に起動する設定を無効にしました。",
        "login_enable_failed_message": "ログイン時に起動する設定を有効にできませんでした。",
        "login_enabled_message": "ログイン時に起動する設定を有効にしました。",
        "microphone_body": (
            "ホットキーを押している間、PtarmiganFlow が音声を取得することを許可します。"
        ),
        "microphone_title": "マイクへのアクセス",
        "model_unavailable_message": (
            "このアプリ版では設定中のモデル {model} は利用できません。"
            "設定からモデルを選択してください。"
        ),
        "open_config_advanced_button": "設定ファイルを開く(上級者向け)",
        "open_system_settings_button": "システム設定を開く",
        "output_clipboard_paste": "クリップボード貼り付け",
        "output_direct_typing": "直接入力",
        "quit_menu": "終了",
        "restart_app_button": "アプリを再起動",
        "restart_failed_message": "アプリを再起動できませんでした。",
        "restart_required_note": (
            "システム設定で許可した直後は、反映のためアプリの再起動が必要な場合があります。"
        ),
        "settings_button": "設定",
        "settings_hotkey_label": "ホットキー",
        "settings_language_label": "言語",
        "settings_load_failed_message": "設定を読み込めませんでした: {error}",
        "settings_menu": "設定",
        "settings_model_label": "モデル",
        "settings_no_models_message": "このアプリ版で利用できる音声モデルがありません。",
        "settings_output_mode_label": "出力方法",
        "settings_save_button": "保存",
        "settings_save_failed_message": "設定を保存できませんでした: {error}",
        "settings_saved_message": "設定を保存しました。反映には音声入力を再起動してください。",
        "settings_validation_error": "設定を保存できませんでした。確認してください: {fields}",
        "settings_window_title": "設定",
        "start_dictation_button": "音声入力を開始",
        "stop_dictation_button": "音声入力を停止",
        "voice_input_started_message": "音声入力を開始しました。",
    },
    "zh": {
        "accessibility_body": "允许 PtarmiganFlow 控制当前文本字段以输入语音输入结果。",
        "accessibility_title": "辅助功能访问权限",
        "allow_button": "允许",
        "all_permissions_granted_started_message": "所有权限已授予。已开始语音输入。",
        "app_setup_title": "PtarmiganFlow 设置",
        "choose_language_body": "选择用于转写的语言，并保存到配置中。",
        "choose_language_title": "选择语言",
        "config_opened_message": "已打开配置文件: {path}",
        "daemon_not_running_message": "语音输入守护进程尚未运行。",
        "daemon_start_failed_message": "无法开始语音输入: {error}",
        "dictation_running_menu": "语音输入 运行中",
        "dictation_stopped_message": "已停止语音输入。",
        "dictation_stopped_menu": "语音输入 已停止",
        "download_complete_message": "下载完成。",
        "download_failed_message": "模型下载失败: {error}",
        "download_in_progress_message": "正在下载模型... {percent}",
        "download_preparing_message": "正在准备模型...",
        "dictionary_add_exact_button": "添加完全匹配",
        "dictionary_add_regex_button": "添加正则表达式",
        "dictionary_canonical_label": "规范写法",
        "dictionary_candidates_patterns_label": "候选/模式(逗号分隔)",
        "dictionary_default_candidate": "候选",
        "dictionary_default_pattern": "模式",
        "dictionary_delete_button": "删除",
        "dictionary_editor_title": "转换词典",
        "dictionary_exact_rules_title": "完全匹配规则",
        "dictionary_invalid_rule_message": (
            "无效的词典规则: [{section}] {key} {pattern}: {message}"
        ),
        "dictionary_load_failed_message": "无法加载转换词典: {error}",
        "dictionary_new_exact_rule": "新的完全匹配规则",
        "dictionary_new_regex_rule": "新的正则表达式规则",
        "dictionary_no_rules": "暂无规则",
        "dictionary_regex_rules_title": "正则表达式规则",
        "dictionary_save_button": "保存",
        "dictionary_save_failed_message": "无法保存转换词典: {error}",
        "dictionary_saved_message": "已保存。请重启语音输入以应用更改。",
        "done_body": "设置已完成。可以开始语音输入或调整设置。",
        "done_title": "语音输入已就绪",
        "edit_dictionary_menu": "编辑转换词典",
        "grant_permissions_message": "开始语音输入前，请授予所有权限。",
        "input_monitoring_body": "允许 PtarmiganFlow 检测一键通话热键。",
        "input_monitoring_title": "输入监控",
        "language_chinese": "中文",
        "language_english": "英语",
        "language_japanese": "日语",
        "language_save_failed_message": "无法保存语言设置: {error}",
        "language_saved_message": "已将语言设置保存到 {path}。",
        "login_at_startup_button": "登录时启动",
        "login_at_startup_menu": "登录时启动",
        "login_disable_failed_message": "无法禁用登录时启动。",
        "login_disabled_message": "已禁用登录时启动。",
        "login_enable_failed_message": "无法启用登录时启动。",
        "login_enabled_message": "已启用登录时启动。",
        "microphone_body": "允许 PtarmiganFlow 在按住热键时采集音频。",
        "microphone_title": "麦克风访问权限",
        "model_unavailable_message": (
            "此应用版本无法使用当前设置的模型 {model}。请在设置中选择模型。"
        ),
        "open_config_advanced_button": "打开配置文件(高级)",
        "open_system_settings_button": "打开系统设置",
        "output_clipboard_paste": "剪贴板粘贴",
        "output_direct_typing": "直接输入",
        "quit_menu": "退出",
        "restart_app_button": "重新启动应用",
        "restart_failed_message": "无法重新启动应用。",
        "restart_required_note": (
            "如果刚刚在系统设置中授予了此权限，可能需要重新启动应用才能生效。"
        ),
        "settings_button": "设置",
        "settings_hotkey_label": "热键",
        "settings_language_label": "语言",
        "settings_load_failed_message": "无法加载设置: {error}",
        "settings_menu": "设置",
        "settings_model_label": "模型",
        "settings_no_models_message": "此应用版本没有可用的语音模型。",
        "settings_output_mode_label": "输出方式",
        "settings_save_button": "保存",
        "settings_save_failed_message": "无法保存设置: {error}",
        "settings_saved_message": "设置已保存。请重启语音输入以应用更改。",
        "settings_validation_error": "无法保存设置。请检查: {fields}",
        "settings_window_title": "设置",
        "start_dictation_button": "开始语音输入",
        "stop_dictation_button": "停止语音输入",
        "voice_input_started_message": "已开始语音输入。",
    },
}


def strings_for(lang: str) -> dict[str, str]:
    """Return app strings for ``lang`` with English fallback per key."""
    english = ONBOARDING_STRINGS["en"]
    localized = ONBOARDING_STRINGS.get(lang.lower(), english)
    return {key: localized.get(key, english[key]) for key in english}
