"""Runtime ports for daemon orchestration."""

from __future__ import annotations

from collections.abc import Iterator
from typing import Protocol

import numpy as np


class AudioInputPort(Protocol):
    @property
    def is_recording(self) -> bool: ...

    def is_stream_active(self) -> bool: ...

    def start(self) -> None: ...

    def stop(self) -> np.ndarray: ...

    def snapshot(self) -> np.ndarray: ...

    def close(self) -> None: ...


class SpeechToTextPort(Protocol):
    def preflight_model(self) -> str: ...

    def transcribe(self, audio: np.ndarray, sample_rate: int) -> str: ...

    def transcribe_stream(self, audio: np.ndarray, sample_rate: int) -> Iterator[str]: ...

    def supports_realtime_input(self) -> bool: ...

    def maybe_release_idle_resources(self) -> None: ...

    def runtime_status(self) -> str: ...

    def backend_summary(self) -> str: ...

    def close(self) -> None: ...


class TextOutputPort(Protocol):
    def inject(self, text: str) -> bool: ...


class ActivityIndicatorPort(Protocol):
    def show_recording(self) -> None: ...

    def show_processing(self) -> None: ...

    def hide(self) -> None: ...

    def close(self) -> None: ...
